### ISSUE TITLE
Tkinter not found

### ISSUE THREAD

**Issue by glsmith86** [Emy69/CoomerDL#5]
user@user-Aspire-F5-771G:~/CoomerDL$ python main.py 
Traceback (most recent call last):
  File "/home/user/CoomerDL/main.py", line 1, in <module>
    from app.ui import ImageDownloaderApp
  File "/home/user/CoomerDL/app/ui.py", line 3, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

Module tk is installed.

**Comment by glsmith86** [comment]
New error after install the correct module:

user@user-Aspire-F5-771G:~/CoomerDL$ python3 main.py
Traceback (most recent call last):
  File "/home/user/CoomerDL/main.py", line 8, in <module>
    main()
  File "/home/user/CoomerDL/main.py", line 4, in main
    app = ImageDownloaderApp()
  File "/home/user/CoomerDL/app/ui.py", line 23, in __init__
    self.setup_window()
  File "/home/user/CoomerDL/app/ui.py", line 61, in setup_window
    self.iconbitmap("resources/img/window.ico")
  File "/home/user/.local/lib/python3.10/site-packages/customtkinter/windows/ctk_tk.py", line 232, in iconbitmap
    super().wm_iconbitmap(bitmap, default)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2109, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "resources/img/window.ico" not defined

**Comment by Emy69** [comment]
To fix the `self.iconbitmap("resources/img/window.ico")` error on Linux, comment out the following line in the `setup_window` function in `ui.py`:

```python
def setup_window(self):
    window_width, window_height = 1000, 680
    center_x = int((self.winfo_screenwidth() / 2) - (window_width / 2))
    center_y = int((self.winfo_screenheight() / 2) - (window_height / 2))
    self.geometry(f"{window_width}x{window_height}+{center_x}+{center_y}")
    # self.iconbitmap("resources/img/window.ico")  # <-- Comment this line

**Comment by glsmith86** [comment]
That works! Thank You!

**Comment by glsmith86** [comment]
That works! Thank You!
